#!/usr/bin/env bash

#
# Generate riscv-formal check configurations for different svc_rv variants
#
# Creates NAME_checks.cfg files and generates NAME_checks/ directories
# following the naming convention from tb/rv testbenches.
#

set -e

#
# Mode from environment (default: quick)
#
MODE="${RISCV_FORMAL_MODE:-quick}"

#
# Depth profiles
#
if [[ $MODE == "quick" ]]; then
  DEPTH_INSN=10
  DEPTH_INSN_DIV=15
  DEPTH_INSN_DIVU=15
  DEPTH_INSN_REM=15
  DEPTH_INSN_REMU=15
  DEPTH_REG="5 10"
  DEPTH_PC="5 10"
  DEPTH_LIVE="1 10 20"
  DEPTH_UNIQUE="1 10 30"
  DEPTH_CAUSAL="5 10"
  DEPTH_COVER="1 10"
  DEPTH_ILL=10
else
  DEPTH_INSN=20
  DEPTH_INSN_DIV=20
  DEPTH_INSN_DIVU=20
  DEPTH_INSN_REM=20
  DEPTH_INSN_REMU=20
  DEPTH_REG="15 30"
  DEPTH_PC="10 30"
  DEPTH_LIVE="1 10 30"
  DEPTH_UNIQUE="1 10 30"
  DEPTH_CAUSAL="10 30"
  DEPTH_COVER="1 20"
  DEPTH_ILL=20
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

#
# Configuration matrix
# Format: "NAME:PIPE:FWD:FWD_REG:MEM:BPRED:BTB:RAS:EXT_M:EXT_Z"
#
# Memory: 0=SRAM, 1=BRAM
# PIPE: 0=single-cycle, 1=pipelined
# Note: ras implies btb, btb implies bpred
#
CONFIGS=(
  # SRAM pipelined variants (MEM_TYPE=0, PIPELINED=1)
  "sram_fwd:1:1:1:0:0:0:0:0:0"
  "sram:1:0:0:0:0:0:0:0:0"
  "sram_m_fwd:1:1:1:0:0:0:0:1:0"
  "sram_zmmul_fwd:1:1:1:0:0:0:0:0:1"
  "sram_bpred_fwd:1:1:1:0:1:0:0:0:0"
  "sram_btb_fwd:1:1:1:0:1:1:0:0:0"
  "sram_ras_fwd:1:1:1:0:1:1:1:0:0"

  # BRAM variants (MEM_TYPE=1, PIPELINED=1)
  "bram:1:0:0:1:0:0:0:0:0"
  "bram_fwd:1:1:1:1:0:0:0:0:0"
  "bram_m_fwd:1:1:1:1:0:0:0:1:0"
  "bram_zmmul_fwd:1:1:1:1:0:0:0:0:1"
  "bram_bpred_fwd:1:1:1:1:1:0:0:0:0"
  "bram_btb_fwd:1:1:1:1:1:1:0:0:0"
  "bram_ras_fwd:1:1:1:1:1:1:1:0:0"

  # SRAM single-cycle (MEM_TYPE=0, PIPELINED=0)
  "sram_sc:0:0:0:0:0:0:0:0:0"
)

echo "Generating riscv-formal configuration files (mode: $MODE)..."

for cfg in "${CONFIGS[@]}"; do
  IFS=':' read -r NAME PIPE FWD FWD_REG MEM BPRED BTB RAS EXT_M EXT_Z <<<"$cfg"

  cfg_file="${NAME}_checks.cfg"
  echo "  Creating $cfg_file"

  #
  # Build ISA string for [options] section
  #
  ISA="rv32i"
  [[ $EXT_M == "1" ]] && ISA="rv32im"

  #
  # Generate configuration file
  #
  cat >"$cfg_file" <<EOF
# WARNING: This file is AUTO-GENERATED by generate_configs.sh
# Do not edit directly - your changes will be overwritten!
# Edit generate_configs.sh instead and regenerate.

[options]
isa $ISA
nret 1

[depth]
insn      $DEPTH_INSN
insn_div    $DEPTH_INSN_DIV
insn_divu   $DEPTH_INSN_DIVU
insn_rem    $DEPTH_INSN_REM
insn_remu   $DEPTH_INSN_REMU
reg       $DEPTH_REG
pc_fwd    $DEPTH_PC
pc_bwd    $DEPTH_PC
liveness  $DEPTH_LIVE
unique    $DEPTH_UNIQUE
causal    $DEPTH_CAUSAL
cover     $DEPTH_COVER
ill       $DEPTH_ILL

[engines]
smtbmc boolector

[script-defines]
verilog_defaults -add -I@basedir@/../../rtl
verilog_defaults -add -I@basedir@/../../rtl/common
verilog_defaults -add -I@basedir@/../../rtl/rv

[defines]
\`define RISCV_FORMAL_ALIGNED_MEM
\`define RISCV_FORMAL_ALTOPS
\`define RISCV_FORMAL_UMODE
\`define SVC_RV_PIPELINED $PIPE
\`define SVC_RV_FWD $FWD
\`define SVC_RV_FWD_REGFILE $FWD_REG
\`define SVC_RV_MEM_TYPE $MEM
\`define SVC_RV_BPRED $BPRED
\`define SVC_RV_BTB_ENABLE $BTB
\`define SVC_RV_RAS_ENABLE $RAS
\`define SVC_RV_EXT_M $EXT_M
\`define SVC_RV_EXT_ZMMUL $EXT_Z

[verilog-files]
@basedir@/cores/@core@/config.sv
@basedir@/cores/@core@/wrapper.sv
@basedir@/../../rtl/rv/svc_rv.sv

[cover]
always @* if (!reset) cover (channel[0].cnt_insns == 2);
EOF

done

echo ""
echo "Generated ${#CONFIGS[@]} configuration files."
echo ""
echo "To generate checks for a specific config:"
echo "  python3 ../../checks/genchecks.py bram_fwd_checks"
echo ""
echo "To generate all checks:"
echo "  for cfg in *_checks.cfg; do python3 ../../checks/genchecks.py \${cfg%.cfg}; done"
