#!/usr/bin/env bash

#
# Generate riscv-formal check configurations for different svc_rv variants
#
# Creates NAME_checks.cfg files and generates NAME_checks/ directories
# following the naming convention from tb/rv testbenches.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

#
# Configuration matrix
# Format: "NAME:PIPE:FWD:FWD_REG:MEM:BPRED:BTB:RAS:EXT_M:EXT_Z"
#
# Memory: 0=SRAM, 1=BRAM
# PIPE: 0=single-cycle, 1=pipelined
# Note: ras implies btb, btb implies bpred
#
CONFIGS=(
  # SRAM pipelined variants (MEM_TYPE=0, PIPELINED=1) - baseline was SRAM!
  "sram_fwd:1:1:1:0:0:0:0:0:0"
  "sram:1:0:0:0:0:0:0:0:0"
  "sram_m_fwd:1:1:1:0:0:0:0:1:0"
  "sram_zmmul_fwd:1:1:1:0:0:0:0:0:1"
  "sram_bpred_fwd:1:1:1:0:1:0:0:0:0"
  "sram_btb_fwd:1:1:1:0:1:1:0:0:0"
  "sram_ras_fwd:1:1:1:0:1:1:1:0:0"

  # BRAM variants (MEM_TYPE=1, PIPELINED=1)
  "bram:1:0:0:1:0:0:0:0:0"
  "bram_fwd:1:1:1:1:0:0:0:0:0"
  "bram_m_fwd:1:1:1:1:0:0:0:1:0"
  "bram_zmmul_fwd:1:1:1:1:0:0:0:0:1"
  "bram_bpred_fwd:1:1:1:1:1:0:0:0:0"
  "bram_btb_fwd:1:1:1:1:1:1:0:0:0"
  "bram_ras_fwd:1:1:1:1:1:1:1:0:0"

  # SRAM single-cycle (MEM_TYPE=0, PIPELINED=0)
  "sram_sc:0:0:0:0:0:0:0:0:0"
)

echo "Generating riscv-formal configuration files..."

for cfg in "${CONFIGS[@]}"; do
  IFS=':' read -r NAME PIPE FWD FWD_REG MEM BPRED BTB RAS EXT_M EXT_Z <<<"$cfg"

  cfg_file="${NAME}_checks.cfg"
  echo "  Creating $cfg_file"

  #
  # Build ISA string for [options] section
  #
  ISA="rv32i"
  [[ $EXT_M == "1" ]] && ISA="rv32im"

  #
  # Generate configuration file
  #
  cat >"$cfg_file" <<EOF
# WARNING: This file is AUTO-GENERATED by generate_configs.sh
# Do not edit directly - your changes will be overwritten!
# Edit generate_configs.sh instead and regenerate.

[options]
isa $ISA
nret 1

[depth]
# TODO: bump to 20 once everything is passing
insn            10
reg        5    10
pc_fwd    10    20
pc_bwd    10    20
liveness  1  10 40
unique    1  10 30
# FIXME: re-enable when done
# causal    10    30
cover     1     15
ill             10

[engines]
smtbmc boolector

[script-defines]
verilog_defaults -add -I@basedir@/../../rtl
verilog_defaults -add -I@basedir@/../../rtl/common
verilog_defaults -add -I@basedir@/../../rtl/rv

[defines]
\`define RISCV_FORMAL_ALIGNED_MEM
\`define RISCV_FORMAL_ALTOPS
\`define RISCV_FORMAL_UMODE
\`define SVC_RV_PIPELINED $PIPE
\`define SVC_RV_FWD $FWD
\`define SVC_RV_FWD_REGFILE $FWD_REG
\`define SVC_RV_MEM_TYPE $MEM
\`define SVC_RV_BPRED $BPRED
\`define SVC_RV_BTB_ENABLE $BTB
\`define SVC_RV_RAS_ENABLE $RAS
\`define SVC_RV_EXT_M $EXT_M
\`define SVC_RV_EXT_ZMMUL $EXT_Z

[verilog-files]
@basedir@/cores/@core@/config.sv
@basedir@/cores/@core@/wrapper.sv
@basedir@/../../rtl/rv/svc_rv.sv

[cover]
always @* if (!reset) cover (channel[0].cnt_insns == 2);
EOF

done

echo ""
echo "Generated ${#CONFIGS[@]} configuration files."
echo ""
echo "To generate checks for a specific config:"
echo "  python3 ../../checks/genchecks.py bram_fwd_checks"
echo ""
echo "To generate all checks:"
echo "  for cfg in *_checks.cfg; do python3 ../../checks/genchecks.py \${cfg%.cfg}; done"
