#!/usr/bin/env bash

#
# Generate riscv-formal check configurations for cache-backed svc_rv SoC
#
# Creates NAME_checks.cfg files and generates NAME_checks/ directories
# following the naming convention from tb/rv testbenches.
#

set -e

#
# Per-config depth overrides
#
ICACHE_DEPTH_INSN_PIPE=25
ICACHE_DEPTH_REG="1 25"
ICACHE_DEPTH_PC="1 25"
ICACHE_DEPTH_LIVE="1 25 50"
ICACHE_DEPTH_UNIQUE="1 30 35"
ICACHE_DEPTH_CAUSAL="1 25"
ICACHE_DEPTH_COVER="1 25"
ICACHE_DEPTH_ILL=25

DCACHE_DEPTH_INSN_PIPE=20
DCACHE_DEPTH_REG="1 15"
DCACHE_DEPTH_PC="1 20"
DCACHE_DEPTH_LIVE="1 20 40"
DCACHE_DEPTH_UNIQUE="1 10 30"
DCACHE_DEPTH_CAUSAL="1 25"
DCACHE_DEPTH_COVER="1 20"
DCACHE_DEPTH_ILL=25

ICACHE_DCACHE_DEPTH_INSN_PIPE=25
ICACHE_DCACHE_DEPTH_REG="1 25"
ICACHE_DCACHE_DEPTH_PC="1 25"
ICACHE_DCACHE_DEPTH_LIVE="1 25 50"
ICACHE_DCACHE_DEPTH_UNIQUE="1 30 35"
ICACHE_DCACHE_DEPTH_CAUSAL="1 25"
ICACHE_DCACHE_DEPTH_COVER="1 25"
ICACHE_DCACHE_DEPTH_ILL=25

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

#
# Configuration matrix
# Format: "NAME:PIPE:FWD:FWD_REG:BPRED:BTB:RAS:EXT_M:EXT_Z:PC_REG:ICACHE:DCACHE"
#
CONFIGS=(
  "icache:1:1:1:0:0:0:0:0:0:1:0"
  "dcache:1:1:1:0:0:0:0:0:0:0:1"
  "icache_dcache:1:1:1:0:0:0:0:0:0:1:1"
)

echo "Generating riscv-formal configuration files (mode: $MODE)..."

for cfg in "${CONFIGS[@]}"; do
  IFS=':' read -r NAME PIPE FWD FWD_REG BPRED BTB RAS EXT_M EXT_Z PC_REG ICACHE DCACHE <<<"$cfg"

  cfg_file="${NAME}_checks.cfg"
  echo "  Creating $cfg_file"

  #
  # Build ISA string for [options] section
  #
  ISA="rv32i"
  [[ $EXT_M == "1" ]] && ISA="rv32im"

  #
  # Generate configuration file
  #
  DEPTH_INSN_PIPE_CFG=$DEPTH_INSN_PIPE
  DEPTH_REG_CFG=$DEPTH_REG
  DEPTH_PC_CFG=$DEPTH_PC
  DEPTH_LIVE_CFG=$DEPTH_LIVE
  DEPTH_UNIQUE_CFG=$DEPTH_UNIQUE
  DEPTH_CAUSAL_CFG=$DEPTH_CAUSAL
  DEPTH_COVER_CFG=$DEPTH_COVER
  DEPTH_ILL_CFG=$DEPTH_ILL

  case "$NAME" in
    icache)
      DEPTH_INSN_PIPE_CFG=$ICACHE_DEPTH_INSN_PIPE
      DEPTH_REG_CFG=$ICACHE_DEPTH_REG
      DEPTH_PC_CFG=$ICACHE_DEPTH_PC
      DEPTH_LIVE_CFG=$ICACHE_DEPTH_LIVE
      DEPTH_UNIQUE_CFG=$ICACHE_DEPTH_UNIQUE
      DEPTH_CAUSAL_CFG=$ICACHE_DEPTH_CAUSAL
      DEPTH_COVER_CFG=$ICACHE_DEPTH_COVER
      DEPTH_ILL_CFG=$ICACHE_DEPTH_ILL
      ;;
    dcache)
      DEPTH_INSN_PIPE_CFG=$DCACHE_DEPTH_INSN_PIPE
      DEPTH_REG_CFG=$DCACHE_DEPTH_REG
      DEPTH_PC_CFG=$DCACHE_DEPTH_PC
      DEPTH_LIVE_CFG=$DCACHE_DEPTH_LIVE
      DEPTH_UNIQUE_CFG=$DCACHE_DEPTH_UNIQUE
      DEPTH_CAUSAL_CFG=$DCACHE_DEPTH_CAUSAL
      DEPTH_COVER_CFG=$DCACHE_DEPTH_COVER
      DEPTH_ILL_CFG=$DCACHE_DEPTH_ILL
      ;;
    icache_dcache)
      DEPTH_INSN_PIPE_CFG=$ICACHE_DCACHE_DEPTH_INSN_PIPE
      DEPTH_REG_CFG=$ICACHE_DCACHE_DEPTH_REG
      DEPTH_PC_CFG=$ICACHE_DCACHE_DEPTH_PC
      DEPTH_LIVE_CFG=$ICACHE_DCACHE_DEPTH_LIVE
      DEPTH_UNIQUE_CFG=$ICACHE_DCACHE_DEPTH_UNIQUE
      DEPTH_CAUSAL_CFG=$ICACHE_DCACHE_DEPTH_CAUSAL
      DEPTH_COVER_CFG=$ICACHE_DCACHE_DEPTH_COVER
      DEPTH_ILL_CFG=$ICACHE_DCACHE_DEPTH_ILL
      ;;
  esac

  cat >"$cfg_file" <<EOF
# WARNING: This file is AUTO-GENERATED by generate_configs.sh
# Do not edit directly - your changes will be overwritten!
# Edit generate_configs.sh instead and regenerate.

[options]
isa $ISA
nret 1

[depth]
insn      $DEPTH_INSN_PIPE_CFG
reg       $DEPTH_REG_CFG
pc_fwd    $DEPTH_PC_CFG
pc_bwd    $DEPTH_PC_CFG
liveness  $DEPTH_LIVE_CFG
unique    $DEPTH_UNIQUE_CFG
causal    $DEPTH_CAUSAL_CFG
cover     $DEPTH_COVER_CFG
ill       $DEPTH_ILL_CFG

[engines]
smtbmc boolector

[script-defines]
verilog_defaults -add -I@basedir@/../../rtl
verilog_defaults -add -I@basedir@/../../rtl/common
verilog_defaults -add -I@basedir@/../../rtl/axi
verilog_defaults -add -I@basedir@/../../rtl/fifo
verilog_defaults -add -I@basedir@/../../rtl/rv

[defines]
\`define RISCV_FORMAL_ALIGNED_MEM
\`define RISCV_FORMAL_ALTOPS
\`define RISCV_FORMAL_UMODE
\`define FORMAL_NO_SUBMODULES
\`define SVC_RV_PIPELINED $PIPE
\`define SVC_RV_FWD $FWD
\`define SVC_RV_FWD_REGFILE $FWD_REG
\`define SVC_RV_BPRED $BPRED
\`define SVC_RV_BTB_ENABLE $BTB
\`define SVC_RV_RAS_ENABLE $RAS
\`define SVC_RV_EXT_M $EXT_M
\`define SVC_RV_EXT_ZMMUL $EXT_Z
\`define SVC_RV_PC_REG $PC_REG
\`define SVC_RV_CACHE_ICACHE $ICACHE
\`define SVC_RV_CACHE_DCACHE $DCACHE

[verilog-files]
@basedir@/cores/@core@/config.sv
@basedir@/cores/@core@/wrapper.sv
@basedir@/../../rtl/rv/svc_rv_soc_bram_cache.sv
@basedir@/../../rtl/axi/svc_axi_mem.sv

[cover]
always @* if (!reset) cover (channel[0].cnt_insns == 2);
EOF

done

echo ""
echo "Generated ${#CONFIGS[@]} configuration files."
echo ""
echo "To generate checks for a specific config:"
echo "  python3 ../../checks/genchecks.py icache_checks"
echo ""
echo "To generate all checks:"
echo "  for cfg in *_checks.cfg; do python3 ../../checks/genchecks.py \${cfg%.cfg}; done"
